package main

var themes = map[string]map[string]string {

    "Default": {
        "bg":        "white",
        "fg":        "black",
        "white":     "white",
        "black":     "black",
        "red":       "red",
        "green":     "green",
        "yellow":    "yellow",
        "orange":    "orange",
        "blue":      "blue",
        "magenta":   "magenta",
        "cyan":      "cyan",
        "purple":    "purple",
        "gray":      "gray",
        "aqua":      "aqua",
    },

    "OneDark": {
        "bg":        "#1E1F29",
        "fg":        "#ABB2BF",
        "black":     "#282C34",
        "white":     "#ABB2BF",
        "red":       "#E06C75",
        "green":     "#98C379",
        "yellow":    "#D19A66",
        "orange":    "#D19A66",
        "blue":      "#61AFEF",
        "magenta":   "#C678DD",
        "cyan":      "#56B6C2",
    },

    "Dracula": {
        "bg":        "#282A36",
        "fg":        "#BFBFBF",
        "black":     "#000000",
        "white":     "#BFBFBF",
        "red":       "#FF5555",
        "green":     "#50FA7B",
        "yellow":    "#F1FA8C",
        "orange":    "#FFB86C",
        "blue":      "#BD93F9",
        "magenta":   "#FF79C6",
        "cyan":      "#8BE9FD",
    },

    "Monokai": {
        "bg":        "#272822",
        "fg":        "#F8F8F2",
        "black":     "#000000",
        "white":     "#F8F8F2",
        "red":       "#F92672",
        "green":     "#A6E22E",
        "yellow":    "#E6DB74",
        "orange":    "#FD971F",
        "blue":      "#66D9EF",
        "purple":    "#AE81FF",
    },

    "GruvboxLight": {
        "bg":        "#FBF1C7",
        "fg":        "#A89984",
        "white":     "#EBDBB2",
        "red":       "#FB4934",
        "green":     "#B8BB26",
        "yellow":    "#FABD2F",
        "blue":      "#83A598",
        "purple":    "#D3869B",
        "aqua":      "#8EC07C",
        "gray":      "#A89984",
    },

    "GruvboxDark": {
        "bg":        "#282828",
        "fg":        "#EBDBB2",
        "white":     "#EBDBB2",
        "red":       "#CC241D",
        "green":     "#98971A",
        "yellow":    "#D79921",
        "blue":      "#458588",
        "purple":    "#B16286",
        "aqua":      "#689D6A",
        "gray":      "#A89984",
    },

    "SnazzyLight": {
        "bg":        "#FAFBFC",
        "fg":        "#9194A2",
        "red":       "#FF5C57",
        "green":     "#2DAE58",
        "yellow":    "#CF9C00",
        "blue":      "#09A1ED",
        "cyan":      "#13BBB7",
        "magenta":   "#F767BB",
        "gray":      "#9194A2",
    },

    "LaserWave": {
        "bg":        "#27212E",
        "fg":        "#FFFFFF",
        "white":     "#FFFFFF",
        "blue":      "#40B4C4",
        "magenta":   "#EB64B9",
        "violet":    "#B381C5",
        "aqua":      "#74DFC4",
        "purple":    "#91889B",
        "yellow":    "#FFE261",
    },

    "HorizonLight": {
        "bg":        "F9CBBE",
        "fg":        "#1A1C23",
        "black":     "#1A1C23",
        "white":     "#F9CBBE",
        "red":       "#DA103F",
        "green":     "#07DA8C",
        "yellow":    "#F77D26",
        "orange":    "#DC3318",
        "blue":      "#1D8991",
        "cyan":      "#1EAEAE",
        "magenta":   "#E73665",
        "purple":    "#8931B9",
        "brown":     "#AF5427",
    },

    "HorizonDark": {
        "bg":        "#1C1E26",
        "fg":        "#F9CBBE",
        "black":     "#1C1E26",
        "white":     "#F9CBBE",
        "red":       "#F43E5C",
        "green":     "#27D796",
        "yellow":    "#FAB795",
        "orange":    "#F09383",
        "blue":      "#25B2BC",
        "cyan":      "#21BFC2",
        "magenta":   "#E9436F",
        "purple":    "#B877DB",
        "brown":     "#FAB38E",
    },

    "Nord": {
        "bg":        "#2E3440",
        "fg":        "#ECEFF4",
        "white":     "#ECEFF4",
        "red":       "#BF616A",
        "green":     "#A3BE8C",
        "yellow":    "#EBCB8B",
        "orange":    "#D08770",
        "blue":      "#5E81AC",
        "cyan":      "#88C0D0",
        "purple":    "#B48EAD",
    },

    "Synthwave84": {
        "bg":        "#2B213A",
        "fg":        "#FFFFFF",
        "red":       "#FE4450",
        "green":     "#72F1B8",
        "yellow":    "#F97E72",
        "blue":      "#03EDF9",
        "cyan":      "#03EDF9",
        "magenta":   "#FF7EDB",
        "orange":    "#FD8B38",
    },

}
